import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ContentProtector from "./components/ContentProtector";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-be-installed="true">
      <body
        data-liner-extension-version="7.17.1"
        data-new-gr-c-s-check-loaded="14.1248.0"
        data-gr-ext-installed=""
      >
        <Navbar />
        {children}
        <Footer />
        <ContentProtector watermarkText="MY WEBSITE" />
        {/* ⬅ injected here */}
      </body>
    </html>
  );
}
